In [ ]:
# Import libraries

import pandas as pd
import time
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import matplotlib.pyplot as plt 
import os
import logging
from bs4 import BeautifulSoup
import requests

In [2]:
# Install Driver for webscraping
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)

In [ ]:
# get url
page_url = requests.get("https://en.wikipedia.org/wiki/Key_events_of_the_20th_century")

In [6]:
# Create soup and get title

soup = BeautifulSoup(page_url.text, 'html.parser')
print(soup.title)

<title>Key events of the 20th century - Wikipedia</title>

In [7]:
# Create text object with contents
text = soup.get_text()

text = text.encode ('utf-8')

with open('20C_events_article_Wiki.txt', 'wb') as f:
       f.write(text)

In [9]:
# Scraping list of country names 

page_url_countries = 'https://simple.wikipedia.org/wiki/List_of_countries'
driver.get(page_url_countries)

In [10]:
# Target all <a> tags inside <p> tags, inside the main content area
country_elements = driver.find_elements(By.CSS_SELECTOR, "div.mw-parser-output > p > a")

# Extract country names
countries = [el.text for el in country_elements]

In [11]:
for country in countries:
    print(country)

sovereign states
Afghanistan
Albania
Algeria
Andorra
Angola
Antigua and Barbuda
Argentina
Armenia
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brazil
Brunei
Bulgaria
Burkina Faso
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Central African Republic
Chad
Chile
China
Colombia
Comoros
Costa Rica
Côte d'Ivoire
Croatia
Cuba
Cyprus
Czechia
Democratic Republic of the Congo
Denmark
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Eswatini
Ethiopia
Fiji
Finland
France
Gabon
Gambia
Georgia
Germany
Ghana
Greece
Grenada
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Honduras
Hungary
Iceland
India
Indonesia
Iran
Iraq
Ireland
Israel
Italy
Jordan
Japan
Jamaica
Kazakhstan
Kenya
Kiribati
Kuwait
Kyrgyzstan
Laos
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Micronesia
Moldova
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Myanmar
Namibia
Nauru
Nepal
Netherlands
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
North Korea
Norway
Oman
Pakistan
Palau
Palestine
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Qatar
Republic of the Congo
Romania
Russia
Rwanda
Saint Kitts and Nevis
Saint Lucia
Saint Vincent and the Grenadines
Samoa
San Marino
São Tomé and Príncipe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Solomon Islands
Somalia
South Africa
South Korea
South Sudan
Spain
Sri Lanka
Sudan
Suriname
Sweden
Switzerland
Syria
Tajikistan
Tanzania
Thailand
Timor Leste
Togo
Tonga
Trinidad and Tobago
Tunisia
Türkiye
Turkmenistan
Tuvalu
Uganda
Ukraine
United Arab Emirates
United Kingdom
United States
Uruguay
Uzbekistan
Vanuatu
Vatican City
Venezuela
Vietnam
Yemen
Zambia
Zimbabwe
Abkhazia
Artsakh
Akrotiri
Åland Islands
American Samoa
Anguilla
Aruba
Ascension Island
Ashmore and Cartier Islands
Bajo Nuveo Bank
Baker Island
Bermuda
Bouvet Island
British Indian Ocean Territory
British Virgin Islands
Canary Islands
Cayman Islands
Ceuta
Chatham Islands
Chilean Antarctic Territory
Christmas Island
Clipperton Island
Cocos (Keeling) Islands
Cook Islands
Coral Sea Islands
Corsica
Crimea
Curaçao
Dagestan
Dhekelia
Donetsk
Ducie Island
Easter Island
Falkland Islands
Faroe Islands
French Guiana
French Polynesia
French Southern and Antarctic Lands
Galápagos Islands
Gilgit-Baltistan
Greenland
Gibraltar
Guadeloupe
Gagauzia
Guam
Guantanamo Bank
Guernsey
Henderson Island
Herm
Heard Island and McDonald Islands
Hong Kong
Howland Island
Isle of Man
Jan Mayen
Jarvis Island
Jeju Island
Jersey
Jervis Bay
Jethou
Johnston Atoll
Jethou
Juan Fernández Islands
Kaliningrad
Karakalpakstan
Kharkiv
Kherson
Kosovo
Kurdistan
Lihou
Luhansk
Macau
Madeira
Marion Island
Martinique
Mayotte
Melilla
Midway Atoll
Montserrat
Mykolaiv
Adygea
New Caledonia
Niue
Norfolk Island
Northern Cyprus
Northern Ireland
Northern Mariana Islands
Northwest Territories
Nunavut
Oecusse
Oeno Island
Order of Malta
Palmyra Atoll
Peñón de Vélez de la Gomera
Pitcairn Island
Prince Edward Island
Puntland
Puerto Rico
Réunion
Ross Dependency
Saba
Saint Barthélemy
Saint Helena
Saint Martin
Saint Pierre and Miquelon
San Andrés and Providencia
Sark
Scotland
Scott Island
Serranilla Bank
Sevastopol
Sint Eustatius
Sint Maarten
Somaliland
South Georgia
South Ossetia
South Orkney Islands
South Sandwich Islands
South Shetland Islands
Svalbard
Swains Island
Taiwan
Tokelau
Transnistria
Tristan da Cunha
Turks and Caicos Islands
United States Virgin Islands
Wake Island
Wales
Wallis and Futuna
Western Sahara
Yukon
Zaporizhzhia
Agaléga
Amsterdam Island
Aves Island
Alderney
Alto Velo Island
Banc du Geyser
Bear Island
Brecqhou
Canary Islands
Cargados Carajos Shoals
Carriacou
Crozet Islands
Culebra
Desecheo
Glorioso Islands
Heligoland
Mona
Monito
Petite Martinique
Rodrigues Island
Rotuma
Tromelin Island
Vieques
Aksai Chin
Australian Capital Territory
Azad Jammu and Kashmir
John F. Kennedy Memorial
South Tibet
Adélie Land
Argentine Antarctica
Australian Antarctic Territory
Balleny Islands
British Antarctic Territory
Marie Byrd Land
Adjara
Adygea
Altai
Bangsamoro
Bashkortostan

In [12]:
df = pd.DataFrame(countries, columns=["Country"])
df.head(10)

               Country
0     sovereign states
1          Afghanistan
2              Albania
3              Algeria
4              Andorra
5               Angola
6  Antigua and Barbuda
7            Argentina
8              Armenia
9            Australia

In [14]:
# Dropping first row which captured the section heading eroneously 
df.drop(df[df['Country'] == 'sovereign states'].index, 
        inplace=True)
df.head(10)

                Country
1           Afghanistan
2               Albania
3               Algeria
4               Andorra
5                Angola
6   Antigua and Barbuda
7             Argentina
8               Armenia
9             Australia
10              Austria

In [15]:
# saving as csv
df.to_csv("countries.csv", index=False)